----------------------------------------
-- SCRIPT CREATION TABLE DE APPSTOCK
----------------------------------------

SET LINESIZE 150
SET FEEDBACK OFF
SET ECHO OFF
CLEAR SCREEN

PROMPT >>>> DEBUT DU SCRIPT

PROMPT >>>> SUPPRESSION DES TABLES

DROP TABLE CLIENT CASCADE CONSTRAINTS PURGE
/
DROP TABLE COMMANDE CASCADE CONSTRAINTS PURGE
/
DROP TABLE CATEGORIEPRODUIT CASCADE CONSTRAINTS PURGE
/
DROP TABLE PRODUIT CASCADE CONSTRAINTS PURGE
/

PROMPT >>>> SUPPRESSION DES SEQUENCES

DROP SEQUENCE SeqClient
/
DROP SEQUENCE SeqProduit
/
DROP SEQUENCE SeqCommande
/
DROP SEQUENCE SeqCatProd
/

PROMPT >>>> CREATION DES SEQUENCES

CREATE SEQUENCE SeqClient MINVALUE 0 START WITH 1
/
CREATE SEQUENCE SeqProduit MINVALUE 0 START WITH 1
/
CREATE SEQUENCE SeqCommande MINVALUE 0 START WITH 1
/
CREATE SEQUENCE SeqCatProd MINVALUE 0 START WITH 1
/

PROMPT >>>> CREATION DES TABLES


CREATE TABLE CATEGORIEPRODUIT (
  IdCatProd INTEGER,
  LibelleCatProd VARCHAR(30) CONSTRAINT NN_LibelleCatProd NOT NULL,
  CONSTRAINT PK_CATEGORIEPRODUIT PRIMARY KEY(IdCatProd)
)
/

CREATE TABLE CLIENT (
  IdClient INTEGER,
  NomClient VARCHAR(50) CONSTRAINT NN_NomClient NOT NULL,
  PreNomClient VARCHAR(50) CONSTRAINT NN_PreNomClient NOT NULL,
  CPClient CHAR(5) CONSTRAINT NN_CPClient NOT NULL,
  AdresseClient VARCHAR(50) CONSTRAINT NN_AdresseClient NOT NULL,
  VilleClient VARCHAR(30) CONSTRAINT NN_VilleClient NOT NULL,
  CONSTRAINT PK_BANQUE PRIMARY KEY(IdClient)
)
/

CREATE TABLE PRODUIT (
  idProd INTEGER,
  LibelleProd VARCHAR(30),
  IdCatProd INTEGER,
  PrixProd NUMBER(10,2),
  QuantiteStock NUMBER(10,2),
  CONSTRAINT PK_PRODUIT PRIMARY KEY(idProd),
  CONSTRAINT FK_PRODUIT_CATEGORIEPRODUIT FOREIGN KEY(IdCatProd) REFERENCES CATEGORIEPRODUIT(IdCatProd) ON DELETE  SET NULL
)
/

CREATE TABLE COMMANDE (
  IdCommande INTEGER,
  IdProd INTEGER,
  DateCommande DATE,
  QuantiteCommande NUMBER(10,2) CONSTRAINT NN_QuantiteCommande NOT NULL,
  IdClient INTEGER CONSTRAINT NN_IdClient NOT NULL,
  CONSTRAINT PK_COMMANDE PRIMARY KEY(IdCommande),
  CONSTRAINT FK_COMMANDE_CLIENT FOREIGN KEY(IdClient) REFERENCES CLIENT(idClient) ON DELETE CASCADE,
  CONSTRAINT FK_COMMANDE_PRODUIT FOREIGN KEY(IdProd) REFERENCES PRODUIT(IdProd) ON DELETE CASCADE
)
/


PROMPT >>>> INSERTION DES DONNEES DE TEST


INSERT INTO CATEGORIEPRODUIT (IdCatProd,LibelleCatProd) VALUES (SeqCatProd.NEXTVAL, 'AVICULTURE')
/
INSERT INTO CATEGORIEPRODUIT (IdCatProd,LibelleCatProd) VALUES (SeqCatProd.NEXTVAL, 'JARDINAGE')
/
INSERT INTO CATEGORIEPRODUIT (IdCatProd,LibelleCatProd) VALUES (SeqCatProd.NEXTVAL, 'APICULTURE')
/
INSERT INTO CATEGORIEPRODUIT (IdCatProd,LibelleCatProd) VALUES (SeqCatProd.NEXTVAL, 'BRICOLAGE EXTERIEUR')
/
INSERT INTO CATEGORIEPRODUIT (IdCatProd,LibelleCatProd) VALUES (SeqCatProd.NEXTVAL, 'BRICOLAGE INTERIEUR')
/

  
INSERT INTO CLIENT (IdClient,NomClient,PreNomClient,CPClient, AdresseClient,VilleClient) VALUES ( SeqClient.NEXTVAL,'LORDINI', 'PIERRE','14300', '30 chemin de la peroi', 'BAYEUX')
/
INSERT INTO CLIENT (IdClient,NomClient,PreNomClient,CPClient, AdresseClient,VilleClient) VALUES ( SeqClient.NEXTVAL,'PARIK', 'LOUISE','50290', '2 rue de la hautelle', 'ISIGNY')
/
INSERT INTO CLIENT (IdClient,NomClient,PreNomClient,CPClient, AdresseClient,VilleClient) VALUES ( SeqClient.NEXTVAL,'MARCIN', 'ELOISE','50300', '1bis rue du palais', 'CHERBOURG')
/


INSERT INTO PRODUIT (idProd,LibelleProd,IdCatProd,PrixProd,QuantiteStock) VALUES ( SeqProduit.NEXTVAL,'ABREUVOIR POULE 5L', 1, 9.80, 2000)
/
INSERT INTO PRODUIT (idProd,LibelleProd,IdCatProd,PrixProd,QuantiteStock) VALUES ( SeqProduit.NEXTVAL,'PLANCHE COFFRAGE 4M', 3, 7.50, 600)
/
INSERT INTO PRODUIT (idProd,LibelleProd,IdCatProd,PrixProd,QuantiteStock) VALUES ( SeqProduit.NEXTVAL,'BROUETTE 2 ROUES', 2, 59.99, 150)
/  

  
PROMPT >>>> FIN DU SCRIPT


SET FEEDBACK ON
SET ECHO ON